### ISSUE TITLE
no accessToken/location header from fetchAccessToken response

### ISSUE THREAD

**Issue by nightsurge** [GuardianTheater/xbox-clips-for-gamertag-service#1]
Hi Chris,

Have you updated your code at some point? When I attempt to use this, it fails in fetchAccessToken because there is no request.headers.location present, so it is not able to get the access_token and cannot continue.

**Comment by nightsurge** [comment]
Nevermind. Was a 2FA issue on my test account.

**Comment by chrisfried** [comment]
I'm no longer using this as the service for Guardian Theater, anyway. Now using the services behind xboxrecord.us, as I'm a terrible server admin and didn't want to deal with making this scale better.
